### ISSUE TITLE
Incorrect upgrading notes for bitnami/harbor to 12.0.0

### ISSUE THREAD

**Issue by lindhe** [bitnami/charts-docs#102]
https://github.com/bitnami/charts-docs/blob/e432d1790cb282ab56e1bceecedfd765eb4e800a/charts/harbor/_upgrade.md.erb#L22

> `service.tls` map has been renamed to `nginx.tls`. To configure TLS termination with Ingress, set `ingress.tls` parameter.

The upgrading notes for Harbor 12.0.0 speaks about "the `ingress.tls` parameter", but I find no such parameter in 12.1.0.

Did it exist in 12.0.0 and was removed in 12.1.0, or did it never exist? Either way, I feel this needs to be clarified in the upgrading notes to make it possible to configure the release correctly.

**Comment by miguelaeh** [comment]
Hi @lindhe ,
thanks for reporting it.
The new parameters are `ingress.core.tls` and `ingress.notary.tls`.

**Comment by lindhe** [comment]
I just found another devastating error in the upgrading notes:

> `--set postgresql.auth.password=$POSTGRESQL_PASSWORD`

There is no such field. It should be `postgresql.auth.postgresPassword`.

If someone could please test the commands before publishing them, that would be great!

I'm changing the title of this PR so we can track all issues with these notes in one place.

**Comment by lindhe** [comment]
`postgresql.persistence.existingClaim` --> `postgresql.primary.persistence.existingClaim`

**Comment by lindhe** [comment]
Another big improvement would be to also be more consistent with how namespace is set. Or even better: setting it in a variable so it's easy to change for the users when copy-pasting commands.

**Comment by lindhe** [comment]
I'll attempt to create a PR to resolve the issues I've identified.

**Comment by miguelaeh** [comment]
Thanks for the PR!

**Comment by lindhe** [comment]
No worries!

There's actually one more thing that's unclear to me, but I don't know what to make of it. It's probably just me missing something...

We explicitly `--set postgresql.image.tag=$CURRENT_PG_VERSION` to keep the same image for the postgresql pod.  And later we `kubectl delete pod harbor-postgresql-0` but AFAICT we never upgrade again with the new version of the sts. Do we intentionally stay at the earlier version?

**Comment by miguelaeh** [comment]
>We explicitly --set postgresql.image.tag=$CURRENT_PG_VERSION to keep the same image for the postgresql pod. And later we kubectl delete pod harbor-postgresql-0 but AFAICT we never upgrade again with the new version of the sts. Do we intentionally stay at the earlier version?

If I understood it properly, you have certain version of the image set, so it won't change when deleting a pod unless you upgrade the chart with a new version

**Comment by lindhe** [comment]
Never mind, I got the answer in the discussion in #103
