### ISSUE TITLE
It's unclear which form of credentials allow upgrades

### ISSUE THREAD

**Issue by krichter722** [bitnami/charts-docs#38]
I do understand the reason for [Credential errors while upgrading chart releases](https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases), however it's unclear to me from this troubleshooting section whether specifying an existing secret (e.g. `postgresql.existingSecret`) is part of the problem or deemed a solution. In most real-world scenario users are wrapping their chart upgrades in tools like Ansible and they won't write different roles for installing and upgrading the chart since Ansible allows them to avoid this for a good reason. Those users will be very interested in whether they can maintain a secret separately from the chart and pass it through values to Bitnami charts both for installation and upgrades.

I suggest to make that more clear in the linked troubleshooting section.

**Comment by miguelaeh** [comment]
Hi @krichter722 ,
Specifying an existing secret the passwords inside the secret won't be autogenerated by helm so you should not face the issue since the passwords won't change
