### ISSUE TITLE
[Redis][backup-restore] Docs are not clear about persistence

### ISSUE THREAD

**Issue by juan-vg** [bitnami/charts-docs#77]
Doc: [Backup and restore Redis deployments](https://github.com/bitnami/charts-docs/blob/699d92316a14450911817f396b9117a883d99c2c/charts/redis/_backup_restore.md.erb) (699d92316a)

1. At L37: Instead of `Enable AOF` should say `Disable AOF`.

```
        configmap: |-
           # Enable AOF https://redis.io/topics/persistence#append-only-file
           appendonly no
           # Disable RDB persistence, AOF persistence already enabled.
           save ""
```

2. At the end of the doc it's not clear if `appendonly` could/should be enabled again or not.

cc @raquel-campuzano

**Comment by randradas** [comment]
hello @juan-vg thank you for your issue, we strongly like to encourage to collab with the repos, would you mind to send a PR to fix?. In case you don't let me know. Thank you!

**Comment by juan-vg** [comment]
Hey @randradas! I'm not sending PR because I'm clueless about this topic. Honestly, I've opened this issue to get more info. Anyways, if I discover something new I will send updates.

**Comment by juan-vg** [comment]
Hello @randradas! 

For the comment I agree with you. I understand it was a copy&paste from values, but it could lead to misunderstanding about what's being done.

As I told you I need more info but it's not about the first point, but the second.

> 2. At the end of the doc it's not clear if appendonly could/should be enabled again or not.

This is where the doc is unclear about further steps and how to continue the operative.
