### ISSUE TITLE
Add an example for the password file in the `Use A Password File` page

### ISSUE THREAD

**Issue by Socolin** [bitnami/charts-docs#88]
Hello,

About this page: https://docs.bitnami.com/kubernetes/infrastructure/redis/administration/use-password-file/

- Could you add an example of the expected content for `redis-password.yaml` ?
- The documentation say it should be called `redis-password`  but in the command line call it's `redis-password-secret`

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the information!  I think there is a bit of a mistake about the password file. The idea is that the password would not be stored in the environment variable but in a file inside the container.

You can enable this behavior by just executing this command

```
helm install redis bitnami/redis --set usePasswordFile=true
```

**Comment by Socolin** [comment]
Yes this is confusing, I was looking for a way to specify a password manually, I ended up doing it with a secret in kubernetes with a data `redis-password` and then I added 

```
auth.enabled=true
auth.sentinel=true
auth.existingSecret=the-secret-name
auth.existingSecretPasswordKey=redis-password
```

So I think the config keys should be updated and the documentation could be clarified.


Also I had some hard time finding how I can connect to my redis, I'm not using helm directly, I'm using terraform and figuring that the documentation was in fact inside `helm status` is not trivial.

It would be nice to have a page "How to connect" that explain how to get the secret / how to specify one and the difference witht the password file (I still don't know what this is). Also sharing a link or adding a link in a comment to keep a note on "how it works" is easier than refering to a command that someone who never use helm before cannot understand easily.

**Comment by javsalgar** [comment]
Let me explain the difference.

The password can be injected to the container in two different ways 

  - Setting the environment variable REDIS_PASSWORD (default approach)
  - Mounting a file that contains the value of the Redis password. The container would open the file and use the password to initialize Redis.

There are users that prefer the second approach as there are potential security benefits. For example, if an attacker gains access to the Docker/ContainerD daemon, it would be more difficult to get the Redis password by listing the environment variables from all the containers. It is not perfect, but it would make it a bit more difficult.

Thank you so much for the docs feedback, I will let the docs team know. Also, feel free to improve the documentation by submitting a PR to this repository, as these are the files that are consumed by docs.bitnami.com
